# Generated by IEEE CS SLIIT for MCS distribution
FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json tsconfig.json ./
RUN npm ci
COPY src/ ./src/
COPY skills/ ./skills/
COPY assets/ ./assets/
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/skills ./skills
COPY --from=builder /app/assets ./assets
COPY README.md ./

ENV PORT=8080
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s CMD wget -q -O- http://localhost:${PORT}/health || exit 1
ENTRYPOINT ["node", "dist/index.js", "--relay"]
